# Generated by Django 3.0.4 on 2021-06-22 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_report', to='customer.TextReport')),
                ('user_get_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_get_report', to=settings.AUTH_USER_MODEL)),
                ('user_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_report', 'user_get_report')},
                'index_together': {('user_report', 'user_get_report')},
            },
        ),
    ]
