# Generated by Django 3.0.4 on 2021-06-23 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_auto_20210622_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follow', to=settings.AUTH_USER_MODEL)),
                ('user_get_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_get_follow', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_follow', 'user_get_follow')},
                'index_together': {('user_follow', 'user_get_follow')},
            },
        ),
    ]
