# Generated by Django 3.0.4 on 2021-06-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow',
        ),
    ]
