# Generated by Django 3.0.4 on 2021-06-18 03:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200402_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_me', models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_me', to=settings.AUTH_USER_MODEL)),
                ('user_rate', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_rate', 'user_me')},
                'index_together': {('user_rate', 'user_me')},
            },
        ),
    ]
