# Generated by Django 3.0.4 on 2021-06-18 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rateuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rateuser',
            name='user_from',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rateuser',
            name='user_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rateuser',
            unique_together={('user_from', 'user_from')},
        ),
        migrations.AlterIndexTogether(
            name='rateuser',
            index_together={('user_from', 'user_from')},
        ),
        migrations.RemoveField(
            model_name='rateuser',
            name='user_me',
        ),
        migrations.RemoveField(
            model_name='rateuser',
            name='user_rate',
        ),
    ]
