# Generated by Django 3.0.4 on 2021-06-22 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210618_1112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rateuser',
            unique_together={('user_from', 'user_to')},
        ),
        migrations.AlterIndexTogether(
            name='rateuser',
            index_together={('user_from', 'user_to')},
        ),
    ]
